name: 同步 TableBundles
run-name: 构建并部署 TableBundles 资源

on:
  workflow_dispatch:
    inputs:
      check:
        description: "检查状态"
        type: boolean
        default: false

      deploy:
        description: "部署产物"
        type: boolean
        default: true

      update:
        description: "更新状态"
        type: boolean
        default: true

jobs:
  check:
    name: 检查状态
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: 检查状态
        id: check_status
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.check }}" == "true" ]]; then
            url="https://api.bluearchive.cafe/status/check?resource=text"
            sync=$(curl -fsSL --max-time 10 "$url")
            if [[ "$sync" == "true" ]]; then
              echo "已是最新版本"
            fi
          else
            sync="false"
            echo "跳过检查状态"
          fi
          echo "sync=$sync" >> "$GITHUB_OUTPUT"

    outputs:
      sync: ${{ steps.check_status.outputs.sync }}

  build:
    name: 构建产物
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: check
    if: needs.check.outputs.sync == 'false'

    steps:
      - name: 获取版本
        id: get_version
        run: |
          url="https://api.bluearchive.cafe/status/get?resource=text&channel=official"
          version=$(curl -fsSL --max-time 10 "$url")
          echo "正在获取版本: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: 检出仓库
        uses: actions/checkout@v6
        with:
          repository: bluearchive-cafe/clientpatch
          token: ${{ secrets.PAT }}
          sparse-checkout: |
            /*
            !/media/
            !/asset/
          sparse-checkout-cone-mode: false

      - name: 安装软件包
        run: sudo apt-get update && sudo apt-get install -y flatbuffers-compiler

      - name: 配置 Python 环境
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.12
          activate-environment: true

      - name: 安装 Python 依赖
        run: uv pip install -r requirements.txt

      - name: 运行脚本
        env:
          RESOURCE_VERSION: ${{ steps.get_version.outputs.version }}
          SQLCIPHER_KEY: ${{ secrets.SQLCIPHER_KEY }}
        run: python src/table.py

      - name: 上传差异
        uses: actions/upload-artifact@v7
        with:
          name: diff
          path: diff/table/
          retention-days: 14

      - name: 上传产物
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.get_version.outputs.version }}
          path: output/${{ steps.get_version.outputs.version }}/
          retention-days: 1

    outputs:
      version: ${{ steps.get_version.outputs.version }}

  deploy:
    name: 部署产物
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: build
    if: github.event.inputs.deploy != 'false'

    steps:
      - name: 计算版本
        id: calc_version
        run: |
          url="https://api.bluearchive.cafe/version/get?env=pre"
          version=$(curl -fsSL --max-time 10 "$url")
          official=${{ needs.build.outputs.version }}

          IFS=_ read -r la lb lc <<< "$version"
          IFS=_ read -r oa oc <<< "$official"

          if [[ "$la" == "$oa" ]]; then
            version="${oa}_$(printf '%02d' $((10#$lb + 1)))_${oc}"
          else
            version="${oa}_00_${oc}"
          fi

          echo "正在计算版本: $version"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: 下载产物
        uses: actions/download-artifact@v8
        with:
          name: ${{ needs.build.outputs.version }}
          path: output/${{ steps.calc_version.outputs.version }}/

      - name: 部署资源
        uses: wei/rclone@v1
        env:
          RCLONE_CONF: ${{ secrets.RCLONE_CONF }}
        with:
          args: sync output/${{ steps.calc_version.outputs.version }}/ bluearchive-cafe:/clientpatch/${{ steps.calc_version.outputs.version }}/

      - name: 打包产物
        run: |
          mkdir -p release/TableBundles/Catalog
          zip_crc=$(cksum output/${{ steps.calc_version.outputs.version }}/text=cn/voice=jp/media=na/TableBundles/Excel.zip | awk '{print $1}')
          db_crc=$(cksum output/${{ steps.calc_version.outputs.version }}/text=cn/voice=jp/media=na/TableBundles/ExcelDB.db | awk '{print $1}')
          cp output/${{ steps.calc_version.outputs.version }}/text=cn/voice=jp/media=na/TableBundles/Excel.zip release/TableBundles/16300795542385574620_${zip_crc}
          cp output/${{ steps.calc_version.outputs.version }}/text=cn/voice=jp/media=na/TableBundles/ExcelDB.db release/TableBundles/6993339912994747134_${db_crc}
          cp output/${{ steps.calc_version.outputs.version }}/text=cn/voice=jp/media=na/TableBundles/TableCatalog.bytes release/TableBundles/Catalog/TableCatalog.bytes
          cd release/TableBundles
          zip -r -9 ../TableBundles.zip .

      - name: 发布发行版
        uses: softprops/action-gh-release@v3
        with:
          repository: bluearchive-cafe/bluearchive-cafe
          token: ${{ secrets.PAT }}
          tag_name: ${{ steps.calc_version.outputs.version }}
          prerelease: true
          files: release/TableBundles.zip

    outputs:
      version: ${{ steps.calc_version.outputs.version }}

  update:
    name: 更新版本
    runs-on: ubuntu-latest
    timeout-minutes: 1
    needs: deploy
    if: github.event.inputs.update != 'false'

    steps:
      - name: 更新版本
        run: |
          version="${{ needs.deploy.outputs.version }}"
          echo "正在更新版本: $version"
          url="https://api.bluearchive.cafe/version/set?env=pre&version=$version&token=${{ secrets.BLUEARCHIVE_CAFE_TOKEN }}"
          curl -fsSL --max-time 10 "$url" >/dev/null
